name: book_my_saloon
description: A mobile app for booking salon services

# Add the SDK constraint here
environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.1
  cloud_firestore: ^4.8.3
  google_fonts: ^6.1.0
  intl: ^0.18.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true